'use client';

import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDownRight, ArrowUpRight, PiggyBank, WalletCards } from 'lucide-react';
import { money } from '@/lib/api';

const colors=['#2563eb','#059669','#7c3aed','#d97706','#e11d48','#0891b2'];
const tooltipStyle={borderRadius:12,borderColor:'#e2e8f0',boxShadow:'0 10px 25px rgba(15,23,42,.12)'};
function Delta({value, suffix=''}:{value:number|null|undefined;suffix?:string}){if(value===null||value===undefined)return <span className="text-slate-400">Not enough history</span>;const good=value>=0;return <span className={`inline-flex items-center gap-1 text-sm font-medium ${good?'text-emerald-700':'text-rose-700'}`}>{good?<ArrowUpRight size={15}/>:<ArrowDownRight size={15}/>} {Math.abs(value)}{suffix}</span>}
function Empty({children}:{children:React.ReactNode}){return <div className="grid h-64 place-items-center rounded-xl border border-dashed border-slate-200 bg-slate-50 p-6 text-center text-sm text-slate-500">{children}</div>}

export function ReportsSkeleton(){return <div className="mt-6 grid gap-5 lg:grid-cols-2">{Array.from({length:4},(_,index)=><div className="card h-80 animate-pulse bg-slate-100" key={index}/>)}</div>}

export function DetailedReports({data}:{data:any}){
  const worth=data.net_worth, investments=data.investments, living=data.cost_of_living, cash=data.cash_flow;
  return <div className="mt-6 grid gap-5 lg:grid-cols-2">
    <section className="card lg:col-span-2"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="label">Net worth over time</p><p className="metric mt-2">{money(worth.current)}</p></div><div className="text-right"><Delta value={worth.change_percent} suffix="%"/><p className="mt-1 text-xs text-slate-500">{worth.change>=0?'+':''}{money(worth.change)} in this period</p></div></div>{worth.series.length>1?<div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={worth.series}><defs><linearGradient id="worthFill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#2563eb" stopOpacity={.28}/><stop offset="1" stopColor="#2563eb" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#64748b'}}/><YAxis tickFormatter={value=>`$${Math.round(value/1000)}k`} tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#64748b'}}/><Tooltip contentStyle={tooltipStyle} formatter={(value:any,name:any)=>[money(value),name]}/><Area type="monotone" dataKey="net_worth" name="Net worth" stroke="#2563eb" strokeWidth={3} fill="url(#worthFill)"/><Line type="monotone" dataKey="assets" name="Assets" stroke="#059669" strokeWidth={1.5} dot={false}/><Line type="monotone" dataKey="liabilities" name="Liabilities" stroke="#e11d48" strokeWidth={1.5} dot={false}/></AreaChart></ResponsiveContainer></div>:<Empty>More account history will make this trend more useful.</Empty>}<p className="mt-3 text-xs text-slate-500">Hover a point for assets, liabilities, and exact values. Historical points become more precise as PFOS captures daily snapshots.</p></section>
    <section className="card"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Investment performance</h2><p className="mt-1 text-sm text-slate-500">Portfolio value and allocation.</p></div><WalletCards className="text-emerald-700"/></div>{investments.allocation.length?<><div className="mt-5 grid grid-cols-2 gap-3"><div><p className="label">Portfolio value</p><b className="mt-1 block text-xl">{money(investments.current_value)}</b></div><div><p className="label">Simple return</p><Delta value={investments.return_percent} suffix="%"/></div></div><div className="mt-4 h-52"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={investments.allocation} dataKey="value" nameKey="name" innerRadius={52} outerRadius={78} paddingAngle={3}>{investments.allocation.map((_:any,index:number)=><Cell fill={colors[index%colors.length]} key={index}/>)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={(value:any)=>money(value)}/><Legend/></PieChart></ResponsiveContainer></div><p className="text-xs text-slate-500">Net contributions {money(investments.net_contributions)} · return {money(investments.return_amount)}</p></>:<Empty>Connect a brokerage or crypto account to see investment reporting.</Empty>}</section>
    <section className="card"><h2 className="font-semibold">Average cost of living</h2><div className="mt-4 grid grid-cols-3 gap-3 text-sm"><div><p className="label">Average</p><b>{money(living.average_monthly_spend)}</b></div><div><p className="label">Projected</p><b>{money(living.projected_month_end_spend)}</b></div><div><p className="label">Vs. last month</p><Delta value={living.month_over_month_percent} suffix="%"/></div></div>{living.series.length?<div className="mt-5 h-52"><ResponsiveContainer width="100%" height="100%"><BarChart data={living.series}><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{fontSize:11,fill:'#64748b'}}/><YAxis hide/><Tooltip contentStyle={tooltipStyle} formatter={(value:any)=>money(value)}/><Legend/><Bar stackId="spend" dataKey="recurring" name="Recurring / expected" fill="#7c3aed" radius={[3,3,0,0]}/><Bar stackId="spend" dataKey="discretionary" name="Discretionary" fill="#f59e0b" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div>:<Empty>No categorized spending is available for this period.</Empty>}</section>
    <section className="card"><h2 className="font-semibold">Income → savings → expenses</h2><p className="mt-1 text-sm text-slate-500">Current calendar month, using your existing savings engine.</p><div className="mt-6 space-y-4">{[['Income',cash.income,'bg-blue-600'],['Savings',cash.savings,'bg-emerald-600'],['Expenses',cash.expenses,'bg-rose-600']].map(([label,value,color])=><div key={String(label)}><div className="flex justify-between text-sm"><span>{label}</span><b>{money(value as number)}</b></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{width:`${Math.min(100,Math.abs(Number(value))/Math.max(Number(cash.income)||1,1)*100)}%`}}/></div></div>)}</div></section>
    <section className="card"><h2 className="font-semibold">Category breakdown</h2><p className="mt-1 text-sm text-slate-500">Spending and debt purchases in the selected timeframe.</p>{cash.categories.length?<div className="mt-5 space-y-3">{cash.categories.slice(0,6).map((category:any,index:number)=><div key={category.name}><div className="flex justify-between text-sm"><span>{category.name}</span><b>{money(category.value)}</b></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{width:`${category.value/cash.categories[0].value*100}%`,backgroundColor:colors[index%colors.length]}}/></div></div>)}</div>:<Empty>Assign categories to transactions to unlock this report.</Empty>}</section>
  </div>;
}

export function SimpleReports({data}:{data:any}){const worth=data.net_worth,spend=data.simple_mode.spend_target,categories=data.simple_mode.top_categories,ratio=Math.min(100,spend.actual/Math.max(spend.target,1)*100),isUp=worth.change>=0;return <div className="simple-mode mx-auto mt-6 max-w-5xl"><header className="simple-hero"><span className="simple-sparkle">✦</span><p className="font-bold text-emerald-800">Your money story</p><h1>Here’s how things are going.</h1><p>Three clear signs to help you feel on track.</p></header><section className="mt-5 grid gap-5 lg:grid-cols-3"><article className="simple-card lg:col-span-2"><p className="simple-eyebrow">Net worth trend</p><p className="simple-money">{money(worth.current)}</p><p className={isUp?'text-emerald-700':'text-rose-700'}>{isUp?'↑':'↓'} {money(Math.abs(worth.change))} {isUp?'up':'down'} this period.</p><div className="mt-4 h-36"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.simple_mode.net_worth_trend}><Line type="monotone" dataKey="net_worth" stroke={isUp?'#059669':'#e11d48'} strokeWidth={4} dot={false}/><Tooltip contentStyle={tooltipStyle} formatter={(value:any)=>money(value)}/></LineChart></ResponsiveContainer></div></article><article className="simple-card simple-spend"><PiggyBank className="h-10 w-10 text-emerald-700"/><p className="simple-eyebrow mt-3">Monthly spend</p><p className="text-3xl font-black">{money(spend.actual)}</p><p className="mt-2 text-sm">Your guide: {money(spend.target)} ({spend.target_source})</p><div className="simple-meter mt-4"><i style={{width:`${ratio}%`}}/></div><p className="mt-2 text-sm">{ratio<=100?'Looking good—you are within your guide.':'A little over your guide this month.'}</p></article><article className="simple-card lg:col-span-3"><p className="simple-eyebrow">Top spending categories</p>{categories.length?<div className="mt-4 grid gap-3 sm:grid-cols-3">{categories.map((category:any,index:number)=><div className="rounded-2xl bg-white/70 p-4" key={category.name}><p className="text-sm font-bold">{index+1}. {category.name}</p><p className="mt-2 text-xl font-black">{money(category.value)}</p></div>)}</div>:<p className="mt-3 text-sm">Add categories to transactions to see your top spending.</p>}</article></section></div>}
