'use client';

import { useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';

const today=new Date().toLocaleDateString('en-CA');
const addDays=(value:string,days:number)=>{const next=new Date(`${value}T12:00:00`);next.setDate(next.getDate()+days);return next.toLocaleDateString('en-CA');};

export function PayScheduleSetup({open,viewUserId,schedule,onClose,onSaved}:{open:boolean;viewUserId:string;schedule?:any;onClose:()=>void;onSaved:(schedule:any)=>void}){
  const [anchor,setAnchor]=useState(today),[policy,setPolicy]=useState<'current_period'|'next_period'>('current_period'),[saving,setSaving]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(open){setAnchor(schedule?.biweekly_anchor_start_date||today);setPolicy(schedule?.paycheck_availability_policy||'current_period');setError('');}},[open,schedule]);
  const previews=useMemo(()=>[0,14,28].map(offset=>{const start=addDays(anchor,offset);return {start,end:addDays(start,13)};}),[anchor]);
  if(!open)return null;
  const save=async()=>{setSaving(true);setError('');try{const schedule=await api(`/planner-pay-schedule?view_user_id=${viewUserId}`,{method:'PUT',body:JSON.stringify({schedule_type:'biweekly',biweekly_anchor_start_date:anchor,paycheck_availability_policy:policy,is_active:true})});onSaved(schedule);onClose();}catch(caught){setError(caught instanceof Error?caught.message:'Could not save biweekly schedule');}finally{setSaving(false);}};
  return <div className="fixed inset-0 z-[70] flex items-end bg-slate-950/50 sm:items-center sm:justify-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="biweekly-setup-title"><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-t-2xl bg-white p-5 shadow-2xl sm:rounded-2xl"><div className="flex items-start justify-between gap-4"><div><h2 id="biweekly-setup-title" className="text-lg font-semibold">{schedule?.configured?'Edit':'Set up'} every-2-weeks planning</h2><p className="mt-1 text-sm text-slate-500">This affects planner availability only. It never changes imported transaction dates or account balances.</p></div><button type="button" className="rounded p-2 text-slate-500 hover:bg-slate-100" onClick={onClose} aria-label="Close biweekly setup">×</button></div>{error&&<p className="mt-4 rounded bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}<div className="mt-5 grid gap-4"><label className="text-sm"><span className="label block">First 14-day period start</span><input required type="date" className="mt-1 w-full rounded border p-2" value={anchor} onChange={event=>setAnchor(event.target.value)}/><small className="mt-1 block text-slate-500">Choose the start of a known pay period, not necessarily a transaction posting date.</small></label><fieldset className="rounded-xl border p-3"><legend className="px-1 text-sm font-medium">When actual paychecks become available</legend><label className="mt-2 flex gap-2 text-sm"><input type="radio" name="availability-policy" checked={policy==='current_period'} onChange={()=>setPolicy('current_period')}/><span><b>Current period</b><small className="block text-slate-500">A paycheck posted during a 14-day period funds that same planner period.</small></span></label><label className="mt-3 flex gap-2 text-sm"><input type="radio" name="availability-policy" checked={policy==='next_period'} onChange={()=>setPolicy('next_period')}/><span><b>Next period</b><small className="block text-slate-500">A paycheck posted during a period funds the following 14-day planner period.</small></span></label></fieldset><div className="rounded-xl border border-blue-200 bg-blue-50 p-3"><h3 className="text-sm font-semibold text-blue-950">Upcoming planner periods</h3><ol className="mt-2 space-y-1 text-sm text-blue-900">{previews.map((item,index)=><li key={item.start}>{index+1}. {item.start} through {item.end}</li>)}</ol></div></div><div className="mt-5 flex justify-end gap-2"><button type="button" className="rounded border px-3 py-2 text-sm" onClick={onClose}>Cancel</button><button type="button" disabled={saving} className="rounded bg-navy px-4 py-2 text-sm font-medium text-white disabled:opacity-50" onClick={()=>void save()}>{saving?'Saving…':schedule?.configured?'Save schedule':'Save and use every 2 weeks'}</button></div></div></div>;
}
