'use client';
import { useEffect, useState } from 'react';
import { api, money } from '@/lib/api';
type Props={open:boolean;period:'paycheck'|'monthly';anchorDate:string;onClose:()=>void;onChanged:()=>void};
export function PlannerIncomeManager({open,period,anchorDate,onClose,onChanged}:Props){
  const [candidates,setCandidates]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]),[source,setSource]=useState(''),[amount,setAmount]=useState(''),[effective,setEffective]=useState(anchorDate),[note,setNote]=useState(''),[error,setError]=useState('');
  const load=async()=>{try{const [nextCandidates,nextRows]=await Promise.all([api(`/planner-income-allocations/candidates?anchor_date=${anchorDate}`),api(`/planner-income-allocations?period_type=${period}`)]);setCandidates(nextCandidates);setRows(nextRows);setError('');}catch(caught){setError(caught instanceof Error?caught.message:'Could not load paycheck assignments');}};
  useEffect(()=>{if(open){setEffective(anchorDate);void load();}},[open,period,anchorDate]);if(!open)return null;
  const chosen=candidates.find(item=>item.id===source);const save=async()=>{if(!source||!amount)return;try{await api('/planner-income-allocations',{method:'POST',body:JSON.stringify({source_transaction_id:source,period_type:period,effective_period_start:effective,amount:Number(amount),note:note||null})});setSource('');setAmount('');setNote('');await load();onChanged();}catch(caught){setError(caught instanceof Error?caught.message:'Could not assign paycheck');}};
  const remove=async(id:string)=>{if(!window.confirm('Remove this planner paycheck assignment?'))return;try{await api(`/planner-income-allocations/${id}`,{method:'DELETE'});await load();onChanged();}catch(caught){setError(caught instanceof Error?caught.message:'Could not remove assignment');}};
  return <div className="fixed inset-0 z-50 flex items-end bg-slate-950/40 sm:items-center sm:justify-center" role="dialog" aria-modal="true"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-2xl bg-white p-5 shadow-xl sm:max-w-2xl sm:rounded-2xl"><div className="flex justify-between gap-3"><div><h2 className="text-lg font-semibold">Paycheck availability</h2><p className="mt-1 text-sm text-slate-500">Keep the bank posting date intact; assign when the money is available to this planner period.</p></div><button type="button" onClick={onClose} aria-label="Close">×</button></div>{error&&<p className="mt-3 rounded bg-rose-50 p-2 text-sm text-rose-800">{error}</p>}<div className="mt-5 grid gap-2 rounded-xl border p-4 sm:grid-cols-2"><select aria-label="Paycheck source" className="rounded border p-2" value={source} onChange={e=>{setSource(e.target.value);const item=candidates.find(candidate=>candidate.id===e.target.value);setAmount(item?String(item.amount):'');}}><option value="">Select posted paycheck</option>{candidates.map(item=><option key={item.id} value={item.id}>{item.date} · {item.description} · {money(item.amount)}</option>)}</select><input aria-label="Assigned amount" className="rounded border p-2" type="number" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount"/><input aria-label="Available date" className="rounded border p-2" type="date" value={effective} onChange={e=>setEffective(e.target.value)}/><input aria-label="Assignment note" className="rounded border p-2" value={note} onChange={e=>setNote(e.target.value)} placeholder="Note (optional)"/><button type="button" className="rounded bg-navy px-3 py-2 text-sm text-white sm:col-span-2" onClick={()=>void save()}>Assign to planner period</button>{chosen&&<p className="text-xs text-slate-500 sm:col-span-2">Posted {chosen.date}; default paycheck period begins {chosen.default_paycheck_period_start}.</p>}</div><div className="mt-5"><h3 className="font-medium">Saved assignments</h3>{rows.length?<ul className="mt-2 space-y-2">{rows.map(row=><li key={row.id} className="flex items-center justify-between gap-3 border-t py-2 text-sm"><span>{row.source_transaction_date} → {row.effective_period_start} · {row.source_description}{row.note&&<small className="ml-1 text-slate-500">{row.note}</small>}</span><span className="flex gap-2"><b>{money(row.amount)}</b><button type="button" className="text-rose-700 underline" onClick={()=>void remove(row.id)}>Remove</button></span></li>)}</ul>:<p className="mt-2 text-sm text-slate-500">No manual assignments. Late-month payroll uses the automatic next-period default.</p>}</div></div></div>;
}
