'use client';

import { useEffect, useState } from 'react';
import { api, money } from '@/lib/api';

type Props={open:boolean;period:'paycheck'|'monthly';anchorDate:string;onClose:()=>void;onChanged:()=>void};
const emptyAdjustment={effective_period_start:'',amount:'',note:''};

export function RollingCashManager({open,period,anchorDate,onClose,onChanged}:Props){
  const [carryovers,setCarryovers]=useState<any[]>([]),[adjustments,setAdjustments]=useState<any[]>([]),[carryoverAmount,setCarryoverAmount]=useState(''),[carryoverNote,setCarryoverNote]=useState(''),[adjustment,setAdjustment]=useState(emptyAdjustment),[editing,setEditing]=useState<any>(),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const load=async()=>{try{const [starting,manual]=await Promise.all([api(`/planner-carryovers?period_type=${period}`),api(`/planner-adjustments?period_type=${period}`)]);setCarryovers(starting);setAdjustments(manual);setError('');}catch(caught){setError(caught instanceof Error?caught.message:'Could not load planner ledger');}};
  useEffect(()=>{if(open){setAdjustment({...emptyAdjustment,effective_period_start:anchorDate});setEditing(undefined);void load();}},[open,period,anchorDate]);
  if(!open)return null;
  const submitCarryover=async()=>{if(carryoverAmount==='')return;setSaving(true);try{await api('/planner-carryovers',{method:'PUT',body:JSON.stringify({period_type:period,effective_period_start:anchorDate,amount:Number(carryoverAmount),note:carryoverNote||null})});setCarryoverAmount('');setCarryoverNote('');await load();onChanged();}catch(caught){setError(caught instanceof Error?caught.message:'Could not save carryover');}finally{setSaving(false);}};
  const submitAdjustment=async()=>{if(!adjustment.amount||!adjustment.effective_period_start)return;setSaving(true);try{const body={effective_period_start:adjustment.effective_period_start,amount:Number(adjustment.amount),note:adjustment.note||null,...(!editing?{period_type:period}:{})};await api(editing?`/planner-adjustments/${editing.id}`:'/planner-adjustments',{method:editing?'PATCH':'POST',body:JSON.stringify(body)});setAdjustment({...emptyAdjustment,effective_period_start:anchorDate});setEditing(undefined);await load();onChanged();}catch(caught){setError(caught instanceof Error?caught.message:'Could not save adjustment');}finally{setSaving(false);}};
  const removeCarryover=async(id:string)=>{if(!window.confirm('Remove this starting carryover? The planner will recalculate using the prior baseline, if one exists.'))return;try{await api(`/planner-carryovers/${id}`,{method:'DELETE'});await load();onChanged();}catch(caught){setError(caught instanceof Error?caught.message:'Could not remove starting carryover');}};
  const remove=async(id:string)=>{if(!window.confirm('Delete this planner adjustment?'))return;try{await api(`/planner-adjustments/${id}`,{method:'DELETE'});await load();onChanged();}catch(caught){setError(caught instanceof Error?caught.message:'Could not delete adjustment');}};
  return <div className="fixed inset-0 z-50 flex items-end bg-slate-950/40 sm:items-center sm:justify-center" role="dialog" aria-modal="true" aria-label="Manage rolling planner cash"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-2xl bg-white p-5 shadow-2xl sm:max-w-2xl sm:rounded-2xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Rolling cash settings</h2><p className="mt-1 text-sm text-slate-500">These entries are scoped to the active household view and {period} planner only.</p></div><button type="button" className="rounded p-2 text-slate-500 hover:bg-slate-100" onClick={onClose} aria-label="Close">×</button></div>{error&&<p className="mt-3 rounded bg-rose-50 p-2 text-sm text-rose-800">{error}</p>}
    <section className="mt-5 rounded-xl border p-4"><h3 className="font-medium">Starting carryover</h3><p className="mt-1 text-sm text-slate-500">Sets the balance at the start of the period containing {anchorDate}. A later starting balance becomes a new baseline.</p><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_2fr_auto]"><input aria-label="Starting carryover amount" type="number" step="0.01" placeholder="Amount (can be negative)" className="rounded border px-3 py-2" value={carryoverAmount} onChange={e=>setCarryoverAmount(e.target.value)}/><input aria-label="Starting carryover note" placeholder="Note (optional)" className="rounded border px-3 py-2" value={carryoverNote} onChange={e=>setCarryoverNote(e.target.value)}/><button type="button" disabled={saving} onClick={()=>void submitCarryover()} className="rounded bg-navy px-3 py-2 text-sm font-medium text-white">Save</button></div>{carryovers.length>0&&<ul className="mt-3 space-y-1 text-sm">{carryovers.map(item=><li key={item.id} className="flex items-center justify-between gap-3 border-t py-2"><span>{item.effective_period_start}{item.note?` · ${item.note}`:''}</span><span className="flex items-center gap-2"><b>{money(item.amount)}</b><button type="button" className="text-rose-700 underline" onClick={()=>void removeCarryover(item.id)}>Remove</button></span></li>)}</ul>}</section>
    <section className="mt-4 rounded-xl border p-4"><h3 className="font-medium">Manual adjustment</h3><p className="mt-1 text-sm text-slate-500">Use a positive amount to add planner cash, or a negative amount to deduct it.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><input aria-label="Adjustment effective date" type="date" className="rounded border px-3 py-2" value={adjustment.effective_period_start} onChange={e=>setAdjustment({...adjustment,effective_period_start:e.target.value})}/><input aria-label="Adjustment amount" type="number" step="0.01" placeholder="Signed amount" className="rounded border px-3 py-2" value={adjustment.amount} onChange={e=>setAdjustment({...adjustment,amount:e.target.value})}/><input aria-label="Adjustment note" placeholder="Note (optional)" className="rounded border px-3 py-2 sm:col-span-2" value={adjustment.note} onChange={e=>setAdjustment({...adjustment,note:e.target.value})}/></div><div className="mt-3 flex gap-2"><button type="button" disabled={saving} onClick={()=>void submitAdjustment()} className="rounded bg-navy px-3 py-2 text-sm font-medium text-white">{editing?'Update adjustment':'Add adjustment'}</button>{editing&&<button type="button" className="rounded border px-3 py-2 text-sm" onClick={()=>{setEditing(undefined);setAdjustment({...emptyAdjustment,effective_period_start:anchorDate});}}>Cancel</button>}</div>{adjustments.length>0&&<ul className="mt-4 space-y-2">{adjustments.map(item=><li key={item.id} className="flex items-center justify-between gap-3 border-t py-2 text-sm"><span><b>{item.effective_period_start}</b>{item.note&&<small className="ml-2 text-slate-500">{item.note}</small>}</span><span className="flex items-center gap-2"><b className={Number(item.amount)>=0?'text-emerald-700':'text-rose-700'}>{money(item.amount)}</b><button type="button" className="text-navy underline" onClick={()=>{setEditing(item);setAdjustment({effective_period_start:item.effective_period_start,amount:String(item.amount),note:item.note||''});}}>Edit</button><button type="button" className="text-rose-700 underline" onClick={()=>void remove(item.id)}>Delete</button></span></li>)}</ul>}</section>
  </div></div>;
}
