'use client';

import { useEffect, useState } from 'react';
import { PlaidSettings } from '@/components/plaid-settings';
import { Settings, X } from 'lucide-react';
import { api } from '@/lib/api';
import { applyFinancialPrivacy, financialPrivacyKey } from '@/lib/financial-privacy';
import { applySimpleMode } from '@/lib/simple-mode';

type Theme = 'system'|'emerald'|'midnight';
type Tab = 'profile'|'appearance'|'savings'|'household'|'users'|'plaid';
const themes: {id:Theme; name:string; description:string}[] = [
  {id:'system',name:'System default',description:'Clean slate financial workspace.'},
  {id:'emerald',name:'Emerald wealth',description:'Forest accents with high-contrast money values.'},
  {id:'midnight',name:'Midnight obsidian',description:'OLED-friendly low-light review.'},
];
function applyTheme(theme: Theme) { document.documentElement.dataset.theme=theme; localStorage.setItem('pfos_theme',theme); }

export function SettingsDrawer() {
  const [blurFinancial,setBlurFinancial]=useState(false);
  const [open,setOpen]=useState(false), [tab,setTab]=useState<Tab>('profile'), [profile,setProfile]=useState<any>(null);
  const [name,setName]=useState(''), [email,setEmail]=useState(''), [currentPassword,setCurrentPassword]=useState(''), [newPassword,setNewPassword]=useState('');
  const [theme,setTheme]=useState<Theme>('system'), [simpleMode,setSimpleMode]=useState(false), [message,setMessage]=useState('');
  const [users,setUsers]=useState<any[]>([]), [members,setMembers]=useState<any[]>([]), [adminPasswords,setAdminPasswords]=useState<Record<string,string>>({});
  const [memberName,setMemberName]=useState(''), [memberEmail,setMemberEmail]=useState(''), [memberPassword,setMemberPassword]=useState('');
  const [accounts,setAccounts]=useState<any[]>([]), [categories,setCategories]=useState<any[]>([]), [tags,setTags]=useState<any[]>([]), [rules,setRules]=useState<any[]>([]);
  const [ruleType,setRuleType]=useState<'account'|'category'|'tag'>('category'), [ruleTarget,setRuleTarget]=useState('');
  useEffect(()=>{const close=()=>setOpen(false);window.addEventListener('pfos-close-settings',close);return()=>window.removeEventListener('pfos-close-settings',close)},[]);
  const loadRules=()=>api('/savings-rules').then(setRules);
  const loadSavings=async()=>{ const [accountRows,categoryRows,tagRows]=await Promise.all([api('/accounts'),api('/categories'),api('/tags')]); setAccounts(accountRows);setCategories(categoryRows);setTags(tagRows);await loadRules(); };

  useEffect(() => {
    setBlurFinancial(localStorage.getItem(financialPrivacyKey)==='true');
    const savedTheme=(localStorage.getItem('pfos_theme') || 'system') as Theme, savedSimple=localStorage.getItem('pfos_simple_mode')==='true';
    applyTheme(savedTheme); applySimpleMode(savedSimple);
    api('/auth/me').then((user)=>{ setProfile(user);setName(user.display_name);setEmail(user.email);setTheme(user.theme_preference);setSimpleMode(user.simple_mode_enabled);applyTheme(user.theme_preference);applySimpleMode(user.simple_mode_enabled); }).catch(()=>{});
    const show=()=>{setOpen(true);setMessage('');}; window.addEventListener('pfos-open-settings',show); return()=>window.removeEventListener('pfos-open-settings',show);
  },[]);
  useEffect(()=>{ if(!open||!profile)return; void loadSavings().catch((error)=>setMessage(error instanceof Error?error.message:'Could not load savings settings')); if(profile.role==='ADMIN'){ void api('/admin/users').then(setUsers).catch((error)=>setMessage(error instanceof Error?error.message:'Could not load users')); void api('/household/members').then(setMembers).catch((error)=>setMessage(error instanceof Error?error.message:'Could not load household members')); } },[open,profile]);
  useEffect(()=>setRuleTarget(''),[ruleType]);
  const options=ruleType==='account'?accounts:ruleType==='category'?categories:tags;
  const tabs:[Tab,string][]=[['profile','Profile & password'],['appearance','Visual preferences'],['savings','Savings rules'],['plaid','Plaid'],...(profile?.role==='ADMIN'?[['household','Household'],['users','User management']] as [Tab,string][]:[])];
  const fail=(fallback:string)=>(error:unknown)=>setMessage(error instanceof Error?error.message:fallback);
  async function saveProfile(event:React.FormEvent){event.preventDefault();try{await api('/auth/me',{method:'PATCH',body:JSON.stringify({display_name:name,email})});setMessage('Profile saved.');}catch(error){fail('Could not save profile')(error);}}
  async function savePassword(event:React.FormEvent){event.preventDefault();try{await api('/users/me/password',{method:'PATCH',body:JSON.stringify({current_password:currentPassword,new_password:newPassword})});setCurrentPassword('');setNewPassword('');setMessage('Password updated.');}catch(error){fail('Could not update password')(error);}}
  async function chooseTheme(next:Theme){try{applyTheme(next);setTheme(next);await api('/users/me/theme',{method:'PATCH',body:JSON.stringify({theme_preference:next})});setMessage('Theme saved.');}catch(error){fail('Could not save theme')(error);}}
  async function toggleSimple(enabled:boolean){try{applySimpleMode(enabled);setSimpleMode(enabled);await api('/users/me/simple-mode',{method:'PATCH',body:JSON.stringify({simple_mode_enabled:enabled})});setMessage(enabled?'Whimsical Simple Mode is on!':'Standard analytical view restored.');}catch(error){fail('Could not save Simple Mode')(error);}}
  async function addMember(event:React.FormEvent){event.preventDefault();try{await api('/household/members',{method:'POST',body:JSON.stringify({display_name:memberName,email:memberEmail,password:memberPassword})});setMemberName('');setMemberEmail('');setMemberPassword('');setMembers(await api('/household/members'));setMessage('Household member added.');}catch(error){fail('Could not add household member')(error);}}
  async function resetPassword(user:any){const password=adminPasswords[user.id];if(!password)return;try{await api(`/admin/users/${user.id}/password`,{method:'PATCH',body:JSON.stringify({new_password:password})});setAdminPasswords(current=>({...current,[user.id]:''}));setMessage(`Password reset for ${user.display_name}.`);}catch(error){fail('Could not reset password')(error);}}
  async function addRule(event:React.FormEvent){event.preventDefault();if(!ruleTarget)return;try{await api('/savings-rules',{method:'POST',body:JSON.stringify({target_type:ruleType,target_id:ruleTarget})});setRuleTarget('');await loadRules();setMessage('Savings rule added.');}catch(error){fail('Could not add savings rule')(error);}}
  async function removeRule(id:string){try{await api(`/savings-rules/${id}`,{method:'DELETE'});await loadRules();}catch(error){fail('Could not remove savings rule')(error);}}

  return <><button type="button" title="Settings" aria-label="Open settings" onClick={()=>{setOpen(true);setMessage('');}} className="fixed bottom-4 left-4 z-40 rounded-full bg-white p-3 text-navy shadow-lg ring-1 ring-slate-200 transition hover:scale-105 hover:bg-slate-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mint"><Settings size={20}/></button>{open&&<div className="fixed inset-0 z-50 bg-slate-950/40" role="dialog" aria-modal="true" aria-labelledby="settings-title"><aside className="ml-auto flex h-full w-full max-w-xl flex-col bg-white shadow-2xl"><header className="flex items-center justify-between border-b p-5"><div><p className="label">PFOS settings</p><h2 id="settings-title" className="text-xl font-semibold">Settings</h2></div><button type="button" className="rounded p-2 hover:bg-slate-100" onClick={()=>setOpen(false)} aria-label="Close settings"><X/></button></header><div className="flex gap-1 overflow-x-auto border-b p-3">{tabs.map(([id,label])=><button type="button" key={id} onClick={()=>setTab(id)} className={`shrink-0 rounded px-3 py-2 text-sm ${tab===id?'bg-navy text-white':'text-slate-600 hover:bg-slate-100'}`}>{label}</button>)}</div><div className="flex-1 overflow-y-auto p-5">{message&&<p className="mb-4 rounded bg-slate-100 p-3 text-sm" role="status">{message}</p>}
    {tab==='profile'&&<div className="space-y-6"><form onSubmit={saveProfile}><h3 className="font-semibold">Profile</h3><label className="label mt-4 block">Display name</label><input className="mt-1 w-full rounded border p-2" value={name} onChange={event=>setName(event.target.value)} required/><label className="label mt-4 block">Email</label><input className="mt-1 w-full rounded border p-2" type="email" value={email} onChange={event=>setEmail(event.target.value)} required/><button className="mt-4 rounded bg-navy px-4 py-2 text-sm text-white">Save profile</button></form><form className="border-t pt-6" onSubmit={savePassword}><h3 className="font-semibold">Change password</h3><p className="mt-1 text-sm text-slate-500">Requires your current password. New passwords need 10+ characters with a letter and number.</p><label className="label mt-4 block">Current password</label><input className="mt-1 w-full rounded border p-2" type="password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)} required/><label className="label mt-4 block">New password</label><input className="mt-1 w-full rounded border p-2" type="password" minLength={10} value={newPassword} onChange={event=>setNewPassword(event.target.value)} required/><button className="mt-4 rounded bg-navy px-4 py-2 text-sm text-white">Update password</button></form></div>}
    {tab==='plaid'&&<PlaidSettings/>}
    {tab==='appearance'&&<div><h3 className="font-semibold">Visual preferences</h3><label className="mt-5 flex cursor-pointer items-center justify-between gap-4 rounded-2xl border p-4"><span><b className="block">Blur financial numbers</b><span className="mt-1 block text-sm text-slate-500">Keep labels readable while hiding amounts, percentages, and financial inputs. Saved on this device; exports are unchanged.</span></span><input aria-label="Blur financial numbers" role="switch" type="checkbox" className="h-5 w-10 accent-emerald-600" checked={blurFinancial} onChange={event=>{applyFinancialPrivacy(event.target.checked);setBlurFinancial(event.target.checked);}}/></label><p className="mt-1 text-sm text-slate-500">Applied immediately and saved to your profile.</p><label className="mt-5 flex cursor-pointer items-center justify-between rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><span><b className="block text-emerald-950">Whimsical Simple Mode</b><span className="mt-1 block text-sm text-emerald-800">Fun, simple, picture-first view for clear daily insights.</span></span><input className="h-5 w-10 accent-emerald-600" type="checkbox" checked={simpleMode} onChange={event=>void toggleSimple(event.target.checked)}/></label><div className="mt-5 grid gap-3">{themes.map(option=><button type="button" key={option.id} onClick={()=>void chooseTheme(option.id)} className={`rounded-xl border p-4 text-left ${theme===option.id?'border-mint ring-2 ring-mint/40':'border-slate-200'}`}><span className={`mb-3 block h-10 rounded ${option.id==='emerald'?'bg-emerald-700':option.id==='midnight'?'bg-slate-950':'bg-slate-200'}`}/><b>{option.name}</b><span className="mt-1 block text-sm text-slate-500">{option.description}</span></button>)}</div></div>}
    {tab==='savings'&&<div><h3 className="font-semibold">Savings calculation rules</h3><p className="mt-1 text-sm text-slate-500">Mark an account as Savings Direct Deposit on Accounts, or designate a category or tag here.</p><ul className="mt-4 space-y-2 text-sm">{rules.map(rule=><li key={rule.id} className="flex justify-between gap-3 rounded bg-slate-50 p-2"><span><b className="capitalize">{rule.target_type}</b>: {rule.label}</span><button type="button" onClick={()=>void removeRule(rule.id)} className="text-red-700">Remove</button></li>)}{!rules.length&&<li className="text-slate-500">No category or tag rules configured.</li>}</ul><form onSubmit={addRule} className="mt-5 border-t pt-5"><div className="grid gap-3 sm:grid-cols-2"><select className="rounded border p-2" value={ruleType} onChange={event=>setRuleType(event.target.value as typeof ruleType)}><option value="account">Account</option><option value="category">Category</option><option value="tag">Tag</option></select><select className="rounded border p-2" value={ruleTarget} onChange={event=>setRuleTarget(event.target.value)} required><option value="">Select {ruleType}</option>{options.map(option=><option value={option.id} key={option.id}>{option.name}</option>)}</select></div><button className="mt-3 rounded bg-navy px-4 py-2 text-sm text-white">Add savings rule</button></form></div>}
    {tab==='household'&&profile?.role==='ADMIN'&&<div><h3 className="font-semibold">Household members</h3><ul className="mt-4 space-y-2 text-sm">{members.map(member=><li key={member.id} className="flex justify-between rounded bg-slate-50 p-2"><span>{member.display_name}</span><span className="text-slate-500">{member.email}</span></li>)}</ul><form onSubmit={addMember} className="mt-5 border-t pt-5"><h4 className="font-medium">Add household member</h4><input className="mt-3 w-full rounded border p-2" placeholder="Display name" value={memberName} onChange={event=>setMemberName(event.target.value)} required/><input className="mt-3 w-full rounded border p-2" type="email" placeholder="Email" value={memberEmail} onChange={event=>setMemberEmail(event.target.value)} required/><input className="mt-3 w-full rounded border p-2" type="password" minLength={10} placeholder="Temporary password (10+ characters)" value={memberPassword} onChange={event=>setMemberPassword(event.target.value)} required/><button className="mt-4 rounded bg-navy px-4 py-2 text-sm text-white">Add member</button></form></div>}
    {tab==='users'&&profile?.role==='ADMIN'&&<div><h3 className="font-semibold">User management</h3><p className="mt-1 text-sm text-slate-500">Passwords are encrypted hashes and cannot be displayed. You can securely set a replacement password.</p><div className="mt-5 space-y-4">{users.map(user=><section key={user.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><b>{user.display_name}</b><p className="text-sm text-slate-500">{user.email}</p></div><span className={`rounded-full px-2 py-1 text-xs font-medium ${user.role==='ADMIN'?'bg-violet-100 text-violet-800':'bg-slate-100 text-slate-700'}`}>{user.role}</span></div><label className="label mt-4 block">Set replacement password</label><div className="mt-1 flex gap-2"><input className="min-w-0 flex-1 rounded border p-2 text-sm" type="password" minLength={10} placeholder="10+ chars, letter and number" value={adminPasswords[user.id]||''} onChange={event=>setAdminPasswords(current=>({...current,[user.id]:event.target.value}))}/><button type="button" onClick={()=>void resetPassword(user)} className="rounded bg-navy px-3 text-sm text-white">Reset</button></div></section>)}</div></div>}
  </div></aside></div>}</>;
}
