'use client';

import { money } from '@/lib/api';

type Props={data:any;rolling?:any;period:'paycheck'|'monthly';setPeriod:(value:'paycheck'|'monthly')=>void;anchorDate:string;setAnchorDate:(value:string)=>void;savingsRate:number;setSavingsRate:(value:number)=>void;toggleRefund:(refund:any,checked:boolean)=>void};
export function SimpleAvailableCash({data,rolling,period,setPeriod,anchorDate,setAnchorDate,savingsRate,setSavingsRate,toggleRefund}:Props) {
  const income=Number(data.paycheck_amount),actualAutomatedSavings=Number(data.automated_savings_amount),projectedAutomatedSavings=actualAutomatedSavings/.3*(savingsRate/100),free=income-Number(data.total_period_expenses),anticipated=Number(data.anticipated_expense_total||0),anticipatedPaychecks=data.anticipated_paychecks||[];
  const spokenFor=Math.min(100,Math.max(0,Number(data.total_period_expenses)/Math.max(income,1)*100));
  const presets=[['Save a little',15],['Balanced',30],['Super saver',45]] as const;
  return <div className="simple-mode mx-auto max-w-5xl"><header className="simple-hero"><span className="simple-sparkle">✦</span><p className="font-bold text-emerald-800">Your happy money snapshot</p><h1>Let’s make today feel easy.</h1><p>Simple numbers. Same smart PFOS math.</p></header>
    <section className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-3xl bg-white p-4 shadow-sm"><div className="flex rounded-full bg-emerald-50 p-1"><button type="button" onClick={()=>setPeriod('paycheck')} className={period==='paycheck'?'simple-pill-active':'simple-pill'}>This paycheck</button><button type="button" onClick={()=>setPeriod('monthly')} className={period==='monthly'?'simple-pill-active':'simple-pill'}>This month</button></div><label className="text-sm font-medium">Pick a date <input type="date" className="ml-2 rounded-xl border p-2" value={anchorDate} onChange={(event)=>setAnchorDate(event.target.value)}/></label></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-3"><article className={`simple-card simple-spend ${free>=0?'simple-good':'simple-watch'} lg:col-span-2`}><span className="text-5xl">{free>=0?'🐷':'🧺'}</span><p className="simple-eyebrow">Safe to spend right now</p><p className="simple-money">{money(free)}</p><p>{free>=0?'Nice work—this is your flexible money after bills.':'A little tight right now. Review bills or incoming pay.'}</p><div className="simple-meter"><i style={{width:`${Math.min(100,Math.max(0,free/Math.max(income,1)*100))}%`}}/></div></article><article className="simple-card simple-stash"><span className="text-5xl">🌱</span><p className="simple-eyebrow">Money stashed away</p><p className="text-3xl font-black">{money(projectedAutomatedSavings)}</p><p className="mt-2 text-sm">At your {savingsRate}% savings choice.</p></article>
      <article className="simple-card lg:col-span-2"><div className="flex items-start justify-between"><div><span className="text-4xl">🧾</span><p className="simple-eyebrow mt-3">Bills & expected stuff</p><p className="text-2xl font-black">{money(data.total_period_expenses)}</p></div><b className="rounded-full bg-amber-100 px-3 py-1 text-amber-800">{Math.round(spokenFor)}% spoken for</b></div><div className="simple-billbar"><i style={{width:`${spokenFor}%`}}/></div><p className="mt-3 text-sm">🏠 Fixed things · 📅 Expected things · ✨ Prorated things · 💳 Debt items {money(data.debt_line_item_total)}</p><p className="mt-1 text-sm font-medium text-violet-800">🔮 Bills coming up: {money(anticipated)}</p><p className="mt-1 text-xs text-slate-500">Debt purchases through {data.debt_line_item_through} only.</p></article>
      <article className="simple-card"><span className="text-4xl">🪙</span><p className="simple-eyebrow mt-3">Your money carried forward</p><p className="text-3xl font-black">{money(rolling?.current?.ending_rolling_available_cash||0)}</p><p className="mt-2 text-sm">Your planner balance after this period’s free spending and any adjustments.</p></article>
      <article className="simple-card"><span className="text-4xl">💫</span><p className="simple-eyebrow mt-3">Choose your savings vibe</p><div className="mt-3 grid gap-2">{presets.map(([label,value])=><button key={value} type="button" onClick={()=>setSavingsRate(value)} className={`rounded-2xl px-3 py-2 text-sm font-bold ${savingsRate===value?'bg-emerald-600 text-white shadow':'bg-emerald-50 text-emerald-900'}`}>{label} {value}%</button>)}</div><input aria-label="Custom savings percentage" className="mt-4 w-full accent-emerald-600" type="range" min="0" max="80" value={savingsRate} onChange={(event)=>setSavingsRate(Number(event.target.value))}/><p className="text-center text-sm font-bold">{savingsRate}% for future-you</p></article></section>
    {data.refunds.length>0&&<section className="simple-card mt-5"><h2 className="text-xl font-black">✨ Little money-back wins</h2><p className="mt-1 text-sm">Tap a bubble to count it toward your bills.</p><div className="mt-3 flex flex-wrap gap-2">{data.refunds.map((refund:any)=><button type="button" key={refund.id} onClick={()=>toggleRefund(refund,!refund.refund_included)} className={`simple-refund ${refund.refund_included?'simple-refund-on':'simple-refund-off'}`}>{refund.refund_included?'✓':'○'} {refund.description} · {money(refund.amount)}</button>)}</div></section>}
  </div>;
}
