'use client';

import { useEffect, useState } from 'react';
import { api, money } from '@/lib/api';
import { useSimpleMode } from '@/lib/simple-mode';

type Item=Record<string,any>;
const plannerFields=new Set(['internal_transfer','refund_credit','loan_reimbursement','expected','prorated','proration_months']);
const fieldLabels:Record<string,string>={category_id:'Category',tag_ids:'Tags',owner_id:'Owner',essential:'Essential',recurring:'Recurring',internal_transfer:'Internal transfer',refund_credit:'Refund credit',loan_reimbursement:'Loan reimbursement',expected:'Expected expense',prorated:'Prorated expense',proration_months:'Proration months'};

function fieldsFor(suggestion:Item|null){
  if(!suggestion)return {};
  if(Object.keys(suggestion.proposal_data?.fields||{}).length)return suggestion.proposal_data.fields;
  const fields:Item={};
  ['category_id','owner_id','essential','internal_transfer','refund_credit','loan_reimbursement','expected','prorated','proration_months'].forEach(key=>{if(suggestion[key]!==null&&suggestion[key]!==undefined)fields[key]={value:suggestion[key]};});
  if(suggestion.tag_ids?.length)fields.tag_ids={value:suggestion.tag_ids};
  return fields;
}
function plannerImpact(suggestion:Item|null){return Object.keys(fieldsFor(suggestion)).some(key=>plannerFields.has(key));}
function status(transaction:Item){
  const smart=transaction.smart_tagging||{};
  if(smart.applied_rule_id)return ['Rule applied','bg-indigo-100 text-indigo-800'];
  if(smart.suggestion_status==='rejected')return ['Rejected','bg-slate-200 text-slate-700'];
  if(smart.suggestion_status==='pending')return Number(smart.confidence_score||0)>=.9?['Suggested','bg-emerald-100 text-emerald-800']:['Needs review','bg-amber-100 text-amber-800'];
  if(smart.suggestion_status==='applied')return ['Suggested applied','bg-emerald-100 text-emerald-800'];
  return null;
}
export function SmartTaggingChip({transaction}:{transaction:Item}){
  const simple=useSimpleMode(),current=status(transaction);if(!current)return null;
  return <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${current[1]}`}>{simple&&current[0]==='Suggested'?'PFOS recognizes this':current[0]}</span>;
}
function valueLabel(name:string,value:any,categories:Item[],tags:Item[],members:Item[]){
  if(name==='category_id')return categories.find(x=>x.id===value)?.name||'Selected category';
  if(name==='owner_id')return members.find(x=>x.id===value)?.display_name||'Selected household member';
  if(name==='tag_ids')return (value||[]).map((id:string)=>tags.find(x=>x.id===id)?.name||'Tag').join(', ');
  if(name==='proration_months')return `${value} month${Number(value)===1?'':'s'}`;
  return typeof value==='boolean'?(value?'Yes':'No'):String(value);
}

export function SmartTaggingPanel({transaction,categories,tags,members,onChanged}:{transaction:Item;categories:Item[];tags:Item[];members:Item[];onChanged:()=>Promise<void>}){
  const simple=useSimpleMode();const [all,setAll]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[rulePreview,setRulePreview]=useState<Item|null>(null);
  const load=async()=>{setLoading(true);try{const rows=await api(`/transactions/${transaction.id}/classification-suggestions`);setAll(rows);const current=rows.find((x:Item)=>x.status==='pending')||rows[0];setSelected(Object.keys(fieldsFor(current)));setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load Smart Tagging details');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[transaction.id]);
  const suggestion=all.find(x=>x.status==='pending')||all[0]||null, fields=fieldsFor(suggestion),names=Object.keys(fields);
  const update=async()=>{await load();await onChanged();};
  const generate=async()=>{setBusy(true);try{const result=await api(`/transactions/${transaction.id}/historical-classification-suggestion`,{method:'POST'});if(result.result)setError(result.explanation||'An active rule already matches this transaction.');else await update();}catch(e){setError(e instanceof Error?e.message:'Could not check local history');}finally{setBusy(false);}};
  const decide=async(action:'accept'|'reject',partial:boolean)=>{if(!suggestion)return;setBusy(true);try{await api(`/classification-suggestions/${suggestion.id}/${partial?`${action}-fields`:action}`,{method:'POST',body:partial?JSON.stringify({fields:selected}):undefined});await update();}catch(e){setError(e instanceof Error?e.message:`Could not ${action} suggestion`);}finally{setBusy(false);}};
  const previewRule=async()=>{if(!suggestion)return;try{setRulePreview(await api(`/classification-suggestions/${suggestion.id}/always-apply-preview`,{method:'POST',body:JSON.stringify({fields:selected})}));}catch(e){setError(e instanceof Error?e.message:'Accept selected fields before creating a rule');}};
  const createRule=async()=>{if(!suggestion)return;setBusy(true);try{await api(`/classification-suggestions/${suggestion.id}/always-apply`,{method:'POST',body:JSON.stringify({fields:selected})});setRulePreview(null);await update();}catch(e){setError(e instanceof Error?e.message:'Could not create future-only rule');}finally{setBusy(false);}};
  const smart=transaction.smart_tagging||{};
  return <section className="mt-5 border-t pt-4">
    <div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">Smart Tagging</h3><p className="mt-1 text-xs text-slate-500">Uses this household’s local history and rules only. No transaction data is sent to external AI services.</p></div><SmartTaggingChip transaction={transaction}/></div>
    <div className="mt-3 rounded-xl border bg-slate-50 p-3 text-sm"><b>Merchant identity:</b> {smart.merchant_display_name||transaction.description}<p className="mt-1 text-xs text-slate-500">Normalized locally: {smart.normalized_merchant_key||'Not available yet'}</p>{smart.applied_rule_name&&<p className="mt-2 rounded bg-indigo-50 p-2 text-indigo-800"><b>Applied rule:</b> {smart.applied_rule_name}</p>}{smart.explanation&&<p className="mt-2 text-xs text-slate-600">{smart.explanation}</p>}</div>
    {loading?<p className="mt-3 text-sm text-slate-500">Checking local classification history…</p>:!suggestion?<div className="mt-3 rounded-xl border border-dashed p-3 text-sm text-slate-600"><p>{simple?'PFOS has not recognized this one yet.':'No active suggestion is available for this transaction.'}</p><button type="button" disabled={busy} onClick={()=>void generate()} className="mt-2 text-sm font-medium text-navy underline">Check local history</button></div>:<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3">
      <b className="text-sm">{suggestion.status==='pending'?(simple?'PFOS has a possible match':'Suggested classification'):`Suggestion ${suggestion.status}`}</b>
      {!simple&&<p className="mt-1 text-xs text-slate-600">Confidence: {Math.round(Number(suggestion.confidence_score||0)*100)}% · {suggestion.evidence_data?.matching_transactions||0} local matching transactions</p>}
      {plannerImpact(suggestion)&&suggestion.status==='pending'&&<p role="alert" className="mt-3 rounded border border-rose-200 bg-rose-50 p-2 text-xs text-rose-800"><b>Planner impact:</b> approving the highlighted fields can change Available Cash and forecasts. Review each one before approving.</p>}
      <div className="mt-3 space-y-2">{names.map(name=>{const data=fields[name],value=data?.value??data;return <label key={name} className={`flex items-start gap-2 rounded border p-2 text-sm ${plannerFields.has(name)?'border-rose-200 bg-rose-50':''}`}><input type="checkbox" disabled={suggestion.status!=='pending'} checked={selected.includes(name)} onChange={()=>setSelected(current=>current.includes(name)?current.filter(x=>x!==name):[...current,name])}/><span><b>{fieldLabels[name]||name}:</b> {valueLabel(name,value,categories,tags,members)}{plannerFields.has(name)&&<small className="ml-2 font-medium text-rose-700">Planner-impacting</small>}{data?.explanation&&<small className="mt-1 block text-slate-600">{data.explanation}</small>}</span></label>;})}</div>
      {suggestion.status==='pending'&&<div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={busy||!selected.length} onClick={()=>void decide('accept',selected.length!==names.length)} className="rounded bg-emerald-700 px-3 py-2 text-sm font-medium text-white disabled:opacity-50">Accept {selected.length===names.length?'suggestion':'selected'}</button><button type="button" disabled={busy||!selected.length} onClick={()=>void decide('reject',selected.length!==names.length)} className="rounded border border-rose-300 px-3 py-2 text-sm text-rose-700 disabled:opacity-50">Reject {selected.length===names.length?'suggestion':'selected'}</button></div>}
      {suggestion.status==='applied'&&suggestion.source_type==='learned'&&<button type="button" onClick={()=>void previewRule()} className="mt-3 text-sm font-medium text-navy underline">Always apply this to future transactions</button>}
    </div>}
    {rulePreview&&<div className="mt-3 rounded-xl border border-indigo-200 bg-indigo-50 p-3 text-sm"><b>Create future-only rule?</b><p className="mt-1 text-slate-700">Matches {rulePreview.direction} transactions for “{rulePreview.normalized_merchant_key}”. Existing transaction history will not change.</p><div className="mt-3 flex gap-2"><button type="button" disabled={busy} className="rounded bg-navy px-3 py-2 text-white" onClick={()=>void createRule()}>Create rule</button><button type="button" className="rounded border px-3 py-2" onClick={()=>setRulePreview(null)}>Cancel</button></div></div>}
    {error&&<p role="alert" className="mt-3 rounded bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
  </section>;
}

export function SmartTaggingReviewQueue({accounts,onSelectTransaction}:{accounts:Item[];categories?:Item[];tags?:Item[];members?:Item[];onSelectTransaction:(transaction:Item)=>void}){
  const [open,setOpen]=useState(false),[items,setItems]=useState<Item[]>([]),[statusFilter,setStatusFilter]=useState('pending'),[accountId,setAccountId]=useState(''),[startDate,setStartDate]=useState(''),[endDate,setEndDate]=useState(''),[lowOnly,setLowOnly]=useState(false),[selected,setSelected]=useState<string[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const load=async()=>{if(!open)return;setLoading(true);try{const q=new URLSearchParams();if(statusFilter)q.set('status',statusFilter);if(accountId)q.set('account_id',accountId);if(startDate)q.set('start_date',startDate);if(endDate)q.set('end_date',endDate);if(lowOnly)q.set('max_confidence','.89');setItems(await api(`/classification-suggestions?${q}`));setSelected([]);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load Smart Tagging review');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[open,statusFilter,accountId,startDate,endDate,lowOnly]);
  const safe=(item:Item)=>item.status==='pending'&&item.safe_for_auto_apply&&!plannerImpact(item), selectedItems=items.filter(item=>selected.includes(item.id));
  const bulk=async()=>{if(selectedItems.some(item=>!safe(item)))return;setLoading(true);try{await Promise.all(selectedItems.map(item=>api(`/classification-suggestions/${item.id}/accept`,{method:'POST'})));await load();}catch(e){setError(e instanceof Error?e.message:'Could not apply safe suggestions');}finally{setLoading(false);}};
  return <><button type="button" className="rounded border px-3 py-2 text-sm font-medium text-navy" onClick={()=>setOpen(true)}>Review Smart Tagging</button>{open&&<div className="fixed inset-0 z-[80] flex items-end bg-slate-900/50 sm:items-center sm:justify-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="smart-review-title"><div className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-t-2xl bg-white p-5 shadow-xl sm:rounded-2xl">
    <div className="flex items-start justify-between gap-3"><div><h2 id="smart-review-title" className="text-xl font-semibold">Smart Tagging review</h2><p className="mt-1 text-sm text-slate-500">The active Joint or individual view is applied automatically.</p></div><button type="button" aria-label="Close" onClick={()=>setOpen(false)}>×</button></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="text-sm"><span className="label block">Status</span><select className="mt-1 w-full rounded border p-2" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="pending">Pending review</option><option value="applied">Rule applied</option><option value="rejected">Rejected</option></select></label><label className="text-sm"><span className="label block">Account</span><select className="mt-1 w-full rounded border p-2" value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">All accounts</option>{accounts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm"><span className="label block">From</span><input type="date" className="mt-1 w-full rounded border p-2" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label className="text-sm"><span className="label block">To</span><input type="date" className="mt-1 w-full rounded border p-2" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><label className="mt-6 flex items-center gap-2 text-sm"><input type="checkbox" checked={lowOnly} onChange={e=>setLowOnly(e.target.checked)}/>Low confidence only</label></div>
    {selectedItems.length>0&&<div className="mt-3 flex items-center justify-between rounded border border-emerald-200 bg-emerald-50 p-3 text-sm"><span>{selectedItems.length} safe suggestion{selectedItems.length===1?'':'s'} selected.</span><button type="button" disabled={loading||selectedItems.some(item=>!safe(item))} onClick={()=>void bulk()} className="rounded bg-emerald-700 px-3 py-2 text-white disabled:opacity-50">Apply safe fields</button></div>}
    <p className="mt-3 text-xs text-slate-500">Bulk approval is limited to high-confidence, non-planner fields. Planner-impacting suggestions always require individual confirmation.</p>{error&&<p role="alert" className="mt-3 rounded bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    <div className="mt-4 space-y-2">{loading?<p className="p-4 text-sm text-slate-500">Loading local suggestions…</p>:items.map(item=>{const source=item.transaction||{};return <div className="rounded-xl border p-3" key={item.id}><div className="flex gap-3"><input aria-label={`Select ${source.description||'suggestion'}`} type="checkbox" disabled={!safe(item)} checked={selected.includes(item.id)} onChange={()=>setSelected(current=>current.includes(item.id)?current.filter(id=>id!==item.id):[...current,item.id])}/><button type="button" className="min-w-0 flex-1 text-left" onClick={()=>{onSelectTransaction(source);setOpen(false);}}><div className="flex flex-wrap justify-between gap-2"><b>{source.description||'Transaction'}</b><b>{money(source.amount||0)}</b></div><p className="mt-1 text-xs text-slate-500">{source.date} · {source.account_name} · {Math.round(Number(item.confidence_score||0)*100)}% confidence</p><p className="mt-2 text-xs text-slate-600">{item.explanation}</p></button></div>{plannerImpact(item)&&<p className="mt-2 rounded bg-rose-50 p-2 text-xs text-rose-800">Planner-impacting suggestion: open and review it individually.</p>}</div>})}{!loading&&!items.length&&<div className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">No Smart Tagging suggestions match these filters.</div>}</div>
  </div></div>}</>;
}

const emptyRule={name:'',owner_id:'',account_id:'',normalized_merchant_key:'',description_pattern:'',direction:'any',financial_role:'',category_id:'',tag_ids:[] as string[],essential:null as boolean|null,internal_transfer:null as boolean|null,refund_credit:null as boolean|null,expected:null as boolean|null,prorated:null as boolean|null,proration_months:'',priority:'100',is_active:true,planner_automation_approved:false};
export function SmartTaggingRulesManager({accounts,categories,tags,members}:{accounts:Item[];categories:Item[];tags:Item[];members:Item[]}){
  const [open,setOpen]=useState(false),[rules,setRules]=useState<Item[]>([]),[form,setForm]=useState<Item>(emptyRule),[editing,setEditing]=useState<Item|null>(null),[sampleId,setSampleId]=useState(''),[samples,setSamples]=useState<Item[]>([]),[preview,setPreview]=useState<Item|null>(null),[error,setError]=useState('');
  const load=async()=>{if(!open)return;try{const [nextRules,transactionRows]=await Promise.all([api('/classification-rules'),api('/transactions?page_size=100&sort=date_desc')]);setRules(nextRules);setSamples(transactionRows.items||[]);}catch(e){setError(e instanceof Error?e.message:'Could not load rules');}};
  useEffect(()=>{void load();},[open]);
  const set=(key:string,value:any)=>setForm(current=>({...current,[key]:value}));
  const start=(rule?:Item)=>{setEditing(rule||null);setPreview(null);setError('');setForm(rule?{...emptyRule,...rule,owner_id:rule.owner_id||'',account_id:rule.account_id||'',normalized_merchant_key:rule.normalized_merchant_key||'',description_pattern:rule.description_pattern||'',financial_role:rule.financial_role||'',category_id:rule.category_id||'',tag_ids:rule.tag_ids||[],proration_months:rule.proration_months||'',priority:String(rule.priority||100)}:emptyRule);};
  const save=async(e:React.FormEvent)=>{e.preventDefault();try{const body={...form,owner_id:form.owner_id||null,account_id:form.account_id||null,normalized_merchant_key:form.normalized_merchant_key||null,description_pattern:form.description_pattern||null,financial_role:form.financial_role||null,category_id:form.category_id||null,proration_months:form.proration_months?Number(form.proration_months):null,priority:Number(form.priority),source_type:'user_authored'};await api(editing?`/classification-rules/${editing.id}`:'/classification-rules',{method:editing?'PATCH':'POST',body:JSON.stringify(body)});start();await load();}catch(err){setError(err instanceof Error?err.message:'Could not save Smart Tagging rule');}};
  const mutate=async(rule:Item,mode:'toggle'|'delete')=>{try{if(mode==='delete'){if(!window.confirm(`Delete “${rule.name}”? Past transactions remain unchanged.`))return;await api(`/classification-rules/${rule.id}`,{method:'DELETE'});}else await api(`/classification-rules/${rule.id}`,{method:'PATCH',body:JSON.stringify({is_active:!rule.is_active})});await load();}catch(e){setError(e instanceof Error?e.message:'Could not update rule');}};
  const test=async()=>{if(!sampleId)return setError('Select a sample transaction first.');try{setPreview(await api(`/transactions/${sampleId}/classification-preview`));}catch(e){setError(e instanceof Error?e.message:'Could not preview matching');}};
  const plannerConfigured=['internal_transfer','refund_credit','expected','prorated','proration_months'].some(key=>form[key]!==null&&form[key]!==''&&form[key]!==false);
  return <><button type="button" className="rounded border px-3 py-2 text-sm font-medium text-navy" onClick={()=>{setOpen(true);start();}}>Manage Smart Tagging rules</button>{open&&<div className="fixed inset-0 z-[80] flex items-end bg-slate-900/50 sm:items-center sm:justify-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="smart-rules-title"><div className="max-h-[94vh] w-full max-w-5xl overflow-y-auto rounded-t-2xl bg-white p-5 shadow-xl sm:rounded-2xl">
    <div className="flex items-start justify-between gap-3"><div><h2 id="smart-rules-title" className="text-xl font-semibold">Smart Tagging rules</h2><p className="mt-1 text-sm text-slate-500">User-authored rules apply to future new transactions; learned suggestions never rewrite history.</p></div><button type="button" aria-label="Close" onClick={()=>setOpen(false)}>×</button></div>{error&&<p role="alert" className="mt-3 rounded bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><div><div className="flex justify-between"><h3 className="font-medium">Rules</h3><button type="button" className="text-sm text-navy underline" onClick={()=>start()}>New rule</button></div><div className="mt-3 space-y-2">{rules.map(rule=><div className="rounded-xl border p-3 text-sm" key={rule.id}><div className="flex justify-between gap-2"><b>{rule.name}</b><span className="text-xs">{rule.is_active?'Active':'Paused'}</span></div><p className="mt-1 text-xs text-slate-500">Priority {rule.priority} · {rule.owner_id?'Individual':'Joint'} · {rule.normalized_merchant_key||rule.description_pattern}</p><p className="mt-1 text-xs text-slate-500">Outputs: {[rule.category_id&&'Category',...(rule.tags||[]).map((tag:Item)=>tag.name),rule.essential!==null&&'Essential',rule.expected!==null&&'Expected',rule.prorated!==null&&'Prorated'].filter(Boolean).join(', ')||'None'}</p><p className="mt-2 flex gap-3"><button type="button" className="text-xs text-navy underline" onClick={()=>start(rule)}>Edit</button><button type="button" className="text-xs text-navy underline" onClick={()=>void mutate(rule,'toggle')}>{rule.is_active?'Pause':'Resume'}</button><button type="button" className="text-xs text-rose-700 underline" onClick={()=>void mutate(rule,'delete')}>Delete</button></p></div>)}{!rules.length&&<p className="rounded border border-dashed p-4 text-sm text-slate-500">No rules yet.</p>}</div></div>
    <form onSubmit={save} className="rounded-xl border bg-slate-50 p-4"><h3 className="font-medium">{editing?'Edit rule':'New rule'}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm sm:col-span-2"><span className="label block">Name</span><input required className="mt-1 w-full rounded border p-2" value={form.name} onChange={e=>set('name',e.target.value)}/></label><label className="text-sm"><span className="label block">Merchant identity</span><input className="mt-1 w-full rounded border p-2" value={form.normalized_merchant_key} onChange={e=>set('normalized_merchant_key',e.target.value)} placeholder="whole foods"/></label><label className="text-sm"><span className="label block">Description pattern</span><input className="mt-1 w-full rounded border p-2" value={form.description_pattern} onChange={e=>set('description_pattern',e.target.value)} placeholder="Optional regex"/></label><label className="text-sm"><span className="label block">Scope</span><select className="mt-1 w-full rounded border p-2" value={form.owner_id} onChange={e=>set('owner_id',e.target.value)}><option value="">Joint</option>{members.map(member=><option key={member.id} value={member.id}>{member.display_name}</option>)}</select></label><label className="text-sm"><span className="label block">Account</span><select className="mt-1 w-full rounded border p-2" value={form.account_id} onChange={e=>set('account_id',e.target.value)}><option value="">Any matching account</option>{accounts.map(account=><option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label className="text-sm"><span className="label block">Direction</span><select className="mt-1 w-full rounded border p-2" value={form.direction} onChange={e=>set('direction',e.target.value)}><option value="any">Any</option><option value="debit">Debit</option><option value="credit">Credit</option></select></label><label className="text-sm"><span className="label block">Category output</span><select className="mt-1 w-full rounded border p-2" value={form.category_id} onChange={e=>set('category_id',e.target.value)}><option value="">No change</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div>
    <fieldset className="mt-4 rounded border bg-white p-3"><legend className="px-1 text-sm font-medium">Safe outputs</legend><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.essential===true} onChange={e=>set('essential',e.target.checked?true:null)}/>Mark essential</label><details className="mt-2"><summary className="cursor-pointer text-sm text-navy">Tags ({form.tag_ids.length})</summary><div className="mt-2 grid gap-1 sm:grid-cols-2">{tags.map(tag=><label key={tag.id} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={form.tag_ids.includes(tag.id)} onChange={()=>set('tag_ids',form.tag_ids.includes(tag.id)?form.tag_ids.filter((id:string)=>id!==tag.id):[...form.tag_ids,tag.id])}/>{tag.name}</label>)}</div></details></fieldset>
    <fieldset className="mt-4 rounded border border-rose-200 bg-rose-50 p-3"><legend className="px-1 text-sm font-medium text-rose-800">Planner-impacting automation</legend><p className="text-xs text-rose-800">This can change Available Cash and forecasts. It requires an explicit opt-in.</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{[['internal_transfer','Internal transfer'],['refund_credit','Refund credit'],['expected','Expected expense'],['prorated','Prorated expense']].map(([key,label])=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form[key]===true} onChange={e=>set(key,e.target.checked?true:null)}/>{label}</label>)}</div>{form.prorated===true&&<label className="mt-2 block text-sm">Proration months <input className="w-20 rounded border p-1" min="1" type="number" value={form.proration_months} onChange={e=>set('proration_months',e.target.value)}/></label>}{plannerConfigured&&<label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={form.planner_automation_approved} onChange={e=>set('planner_automation_approved',e.target.checked)}/><span><b>I approve automatic planner-impacting outputs.</b><small className="block">Otherwise matching transactions stay pending for review.</small></span></label>}</fieldset>
    <div className="mt-4 rounded border bg-white p-3"><label className="text-sm"><span className="label block">Preview a saved sample</span><select className="mt-1 w-full rounded border p-2" value={sampleId} onChange={e=>setSampleId(e.target.value)}><option value="">Select transaction</option>{samples.map(item=><option key={item.id} value={item.id}>{item.date} · {item.description} · {money(item.amount)}</option>)}</select></label><button type="button" className="mt-2 text-sm text-navy underline" onClick={()=>void test()}>Preview current saved rules</button>{preview&&<p className="mt-2 text-xs text-slate-600">{preview.match?`Matches “${preview.match.name}” (priority ${preview.match.priority}).`:'No saved rule matches this sample. Save this rule first to preview it.'}</p>}</div><button className="mt-4 w-full rounded bg-navy px-4 py-2 text-sm font-medium text-white">{editing?'Save rule':'Create rule'}</button></form>
    </div>
  </div></div>}</>;
}
