'use client';

import { useCallback, useEffect, useState } from 'react';
import { api, money } from '@/lib/api';
import { Protected } from '@/components/protected';
import { loadViewState, saveViewState } from '@/lib/persistent-view';
import { useSimpleMode } from '@/lib/simple-mode';
import { SimpleAvailableCash } from '@/components/simple-available-cash';

const today=new Date().toLocaleDateString('en-CA');
const shiftDate=(value:string,days:number)=>{const next=new Date(`${value}T12:00:00`);next.setDate(next.getDate()+days);return next.toLocaleDateString('en-CA');};
type DebtSort='date-desc'|'date-asc'|'amount-desc'|'amount-asc';

export default function AvailableCashPlanner(){
  const simpleMode=useSimpleMode(); const [period,setPeriod]=useState<'paycheck'|'monthly'>('paycheck'); const [anchorDate,setAnchorDate]=useState(today),[savingsRate,setSavingsRate]=useState(30),[debtSort,setDebtSort]=useState<DebtSort>('date-desc');
  const [data,setData]=useState<any>(),[error,setError]=useState(''),[ready,setReady]=useState(false),[viewVersion,setViewVersion]=useState(0);
  const load=useCallback(()=>api(`/available-cash-planner?period=${period}&anchor_date=${anchorDate}`).then(result=>{setData(result);setError('');}).catch(caught=>setError(caught instanceof Error?caught.message:'Could not load planner')),[period,anchorDate]);
  const restore=useCallback(()=>{const state=loadViewState('available-cash',{period:'paycheck',anchorDate:today,savingsRate:30,debtSort:'date-desc'});setPeriod(state.period as 'paycheck'|'monthly');setAnchorDate(state.anchorDate);setSavingsRate(state.savingsRate);setDebtSort(state.debtSort as DebtSort);setData(undefined);setReady(true);setViewVersion(version=>version+1);},[]);
  useEffect(()=>{restore();window.addEventListener('pfos-view-change',restore);return()=>window.removeEventListener('pfos-view-change',restore);},[restore]);
  useEffect(()=>{if(ready)void load();},[load,ready,viewVersion]);
  useEffect(()=>{if(ready)saveViewState('available-cash',{period,anchorDate,savingsRate,debtSort});},[period,anchorDate,savingsRate,debtSort,ready]);
  const toggleRefund=async(refund:any,checked:boolean)=>{try{await api(`/transactions/${refund.id}/planner-flags`,{method:'PATCH',body:JSON.stringify({refund_included:checked})});await load();}catch(caught){setError(caught instanceof Error?caught.message:'Could not update refund');}};
  const paycheckAmount=Number(data?.paycheck_amount||0), netAfterSavings=paycheckAmount*(1-savingsRate/100), freeSpending=netAfterSavings-Number(data?.total_period_expenses||0);
  const debtItems=[...(data?.debt_line_items||[])].sort((a:any,b:any)=>debtSort==='amount-desc'?Number(b.amount)-Number(a.amount):debtSort==='amount-asc'?Number(a.amount)-Number(b.amount):debtSort==='date-asc'?String(a.date).localeCompare(String(b.date)):String(b.date).localeCompare(String(a.date)));
  const navigate=(direction:-1|1)=>{if(data)setAnchorDate(shiftDate(direction<0?data.period_start:data.period_end,direction));};
  if(simpleMode)return <Protected>{error&&<p className="m-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!data?<p className="p-8">Loading your simple money view…</p>:<SimpleAvailableCash data={data} period={period} setPeriod={setPeriod} anchorDate={anchorDate} setAnchorDate={setAnchorDate} savingsRate={savingsRate} setSavingsRate={setSavingsRate} toggleRefund={toggleRefund}/>}</Protected>;
  return <Protected><header><p className="label">Planning</p><h1 className="text-3xl font-bold">Available Cash Planner</h1><p className="mt-1 text-slate-500">Plan available spending without changing your saved savings configuration.</p></header>
    <section className="card mt-6"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex rounded-lg border p-0.5 text-sm"><button type="button" onClick={()=>setPeriod('paycheck')} className={`rounded-md px-3 py-2 ${period==='paycheck'?'bg-navy text-white':'text-slate-600'}`}>Paycheck view</button><button type="button" onClick={()=>setPeriod('monthly')} className={`rounded-md px-3 py-2 ${period==='monthly'?'bg-navy text-white':'text-slate-600'}`}>Monthly view</button></div><div className="flex items-center gap-2"><button type="button" className="rounded border px-3 py-2 text-sm" onClick={()=>navigate(-1)}>Previous</button><input aria-label="Planner history date" type="date" className="rounded border p-2 text-sm" value={anchorDate} onChange={event=>setAnchorDate(event.target.value)}/><button type="button" className="rounded border px-3 py-2 text-sm" onClick={()=>setAnchorDate(today)}>Today</button><button type="button" className="rounded border px-3 py-2 text-sm" onClick={()=>navigate(1)}>Next</button></div></div>{data&&<p className="mt-3 text-sm text-slate-500">{data.period_label}: {data.period_start} through {data.period_end}</p>}</section>
    {error&&<p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!data?<p className="mt-8">Loading planner…</p>:<><section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[period==='paycheck'?'Paycheck amount':'Paycheck total',paycheckAmount],['Automated savings',data.automated_savings_amount],['Period expenses',data.total_period_expenses]].map(([label,value])=><div className="card" key={String(label)}><p className="label">{label}</p><p className="metric mt-2">{money(value)}</p></div>)}<div className={`card ${freeSpending>=0?'ring-1 ring-emerald-200':'ring-1 ring-rose-200'}`}><p className="label">Free spending</p><p className={`metric mt-2 ${freeSpending>=0?'text-emerald-700':'text-rose-700'}`}>{money(freeSpending)}</p></div></section>
      <section className="card mt-5"><div className="flex items-center justify-between gap-4"><div><h2 className="font-semibold">Savings what-if</h2><p className="text-sm text-slate-500">Visual only—Free spending uses paycheck income after this choice. Automated savings stays separate.</p></div><b className="text-lg">{savingsRate}%</b></div><input aria-label="Savings rate" className="mt-4 w-full accent-emerald-600" type="range" min="0" max="80" step="1" value={savingsRate} onChange={event=>setSavingsRate(Number(event.target.value))}/></section>
      <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="card"><h2 className="font-semibold">Income inputs</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt>{period==='monthly'?'Paycheck total':'Paycheck amount'}</dt><dd>{money(data.paycheck_amount)}</dd></div><details className="rounded-md border border-blue-100 bg-blue-50/40 px-3 py-2"><summary className="cursor-pointer text-sm font-medium text-blue-800">Paycheck sources ({data.paycheck_sources.length})</summary>{data.paycheck_sources.length?data.paycheck_sources.map((source:any)=><p className="mt-2 flex justify-between text-sm" key={source.id}><span>{source.description} <small>{source.date} · {source.account_name}</small></span><b>{money(source.amount)}</b></p>):<p className="mt-2 text-sm text-slate-500">No paycheck credits in this period.</p>}</details><div className="flex justify-between"><dt>Automated savings</dt><dd>{money(data.automated_savings_amount)}</dd></div><details className="rounded-md border border-emerald-100 bg-emerald-50/40 px-3 py-2"><summary className="cursor-pointer text-sm font-medium text-emerald-800">Automated savings sources ({data.automated_savings_sources.length})</summary>{data.automated_savings_sources.length?data.automated_savings_sources.map((source:any)=><p className="mt-2 flex justify-between text-sm" key={source.id}><span>{source.description} <small>{source.date} · {source.account_name}</small></span><b>{money(source.amount)}</b></p>):<p className="mt-2 text-sm text-slate-500">No automated savings credits in this period.</p>}</details><div className="flex justify-between border-t pt-3 font-semibold"><dt>{period==='monthly'?'NMP monthly':'NMP per paycheck'}</dt><dd>{money(period==='monthly'?data.net_monthly_pay:data.nmp_paycheck)}</dd></div></dl><p className="mt-3 text-xs text-slate-500">Refunds are applied as expense credits below, not income.</p></div>
      <div className="card"><h2 className="font-semibold">Expense inputs</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt>Fixed, expected & prorated</dt><dd>{money(data.regular_expected_prorated_expenses)}</dd></div><p className="text-xs text-slate-500">Fixed {money(data.fixed_regular_expenses)} · Expected {money(data.expected_expenses)} · Prorated {money(data.prorated_expenses)}</p><details className="rounded-md border border-rose-100 bg-rose-50/40 px-3 py-2"><summary className="cursor-pointer text-sm font-medium text-rose-800">Fixed, expected & prorated breakdown ({data.expense_input_sources.length})</summary>{data.expense_input_sources.length?<ul className="mt-3 space-y-2 border-t border-rose-100 pt-2">{data.expense_input_sources.map((source:any)=><li className="flex items-start justify-between gap-3 text-sm" key={`${source.type}-${source.id}`}><span><b className="block">{source.description}</b><small className="text-slate-500">{source.type} · {source.date} · {source.account_name}{source.type==='Prorated'&&` · ${source.proration_months}-month spread`}</small></span><b className="text-rose-800">{money(source.period_amount)}</b></li>)}</ul>:<p className="mt-2 text-sm text-slate-500">No fixed, expected, or prorated inputs in this period.</p>}</details><div className="flex justify-between"><dt>Debt line items</dt><dd>{money(data.debt_line_item_total)}</dd></div><div className="flex justify-between border-t pt-3"><dt>Gross period expenses</dt><dd>{money(data.gross_total_period_expenses)}</dd></div><div className="flex justify-between rounded-md bg-emerald-50 px-2 py-2 text-emerald-800"><dt>Included refund credit</dt><dd>-{money(data.refund_expense_offset)}</dd></div><div className="flex justify-between border-t pt-3 font-semibold"><dt>Total period expenses</dt><dd>{money(data.total_period_expenses)}</dd></div></dl></div></section>
      <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="card"><h2 className="font-semibold">Refund itemization</h2><p className="mt-1 text-sm text-slate-500">Only marked refunds appear here. Toggle inclusion to decrease total period expenses.</p>{data.refunds.length?<ul className="mt-4 space-y-3">{data.refunds.map((refund:any)=><li className="flex items-center justify-between gap-3 border-t pt-3" key={refund.id}><label className="flex min-w-0 items-center gap-3 text-sm"><input type="checkbox" checked={refund.refund_included} onChange={event=>void toggleRefund(refund,event.target.checked)}/><span><b className="block">{refund.description}</b><small className="text-slate-400">{refund.date} · {refund.account_name}</small></span></label><b>{money(refund.amount)}</b></li>)}</ul>:<p className="mt-4 text-sm text-slate-500">No positive transactions are marked as refunds in this period.</p>}</div><div className="card"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Debt line items</h2><label className="flex items-center gap-2 text-sm text-slate-600">Sort <select aria-label="Sort debt line items" className="rounded border bg-white px-2 py-1.5 text-sm" value={debtSort} onChange={event=>setDebtSort(event.target.value as DebtSort)}><option value="date-desc">Date: newest</option><option value="date-asc">Date: oldest</option><option value="amount-desc">Amount: highest</option><option value="amount-asc">Amount: lowest</option></select></label></div><p className="mt-1 text-sm text-slate-500">Debt-account purchases through {data.debt_line_item_through}; expected and prorated items are grouped above. Payoff transfers are excluded.</p>{debtItems.length?<ul className="mt-4 space-y-3">{debtItems.map((item:any)=><li className="flex justify-between gap-3 border-t pt-3 text-sm" key={item.id}><span><b className="block">{item.description}</b><small className="text-slate-400">{item.date} · {item.account_name}</small></span><b>{money(item.amount)}</b></li>)}</ul>:<p className="mt-4 text-sm text-slate-500">No separate debt line items through this date.</p>}</div></section></>}</Protected>;
}
