'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { api, money } from '@/lib/api';
import { Protected } from '@/components/protected';
import { loadViewState, saveViewState } from '@/lib/persistent-view';

const today=new Date().toISOString().slice(0,10), monthStart=`${today.slice(0,8)}01`;
export default function CategoryTracker(){
  const [startDate,setStartDate]=useState(monthStart),[endDate,setEndDate]=useState(today),[data,setData]=useState<any>(null),[visible,setVisible]=useState<string[]>([]),[selected,setSelected]=useState<any>(null),[details,setDetails]=useState<any[]>([]),[error,setError]=useState(''),[ready,setReady]=useState(false),[visibilityConfigured,setVisibilityConfigured]=useState(false),[viewVersion,setViewVersion]=useState(0);
  const [managerOpen,setManagerOpen]=useState(false),[newName,setNewName]=useState(''),[newKind,setNewKind]=useState('expense'),[newParentId,setNewParentId]=useState(''),[editing,setEditing]=useState<any>(null),[editName,setEditName]=useState(''),[deleting,setDeleting]=useState<any>(null),[replacementId,setReplacementId]=useState(''),[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{try{const result=await api(`/category-tracker?start_date=${startDate}&end_date=${endDate}`);setData(result);setVisible(current=>visibilityConfigured?current:result.categories.map((category:any)=>category.id||'uncategorized'));setError('');}catch(caught){setError(caught instanceof Error?caught.message:'Could not load category totals');}},[startDate,endDate,visibilityConfigured]);
  const restore=useCallback(()=>{const state=loadViewState('category-tracker',{startDate:monthStart,endDate:today,visible:undefined as string[]|undefined});setStartDate(state.startDate);setEndDate(state.endDate);setVisible(state.visible||[]);setVisibilityConfigured(Array.isArray(state.visible));setData(null);setSelected(null);setDetails([]);setReady(true);setViewVersion(version=>version+1);},[]);
  useEffect(()=>{restore();window.addEventListener('pfos-view-change',restore);return()=>window.removeEventListener('pfos-view-change',restore);},[restore]);
  useEffect(()=>{if(ready)void load();},[ready,load,viewVersion]);
  useEffect(()=>{if(ready&&visibilityConfigured)saveViewState('category-tracker',{startDate,endDate,visible});},[startDate,endDate,visible,ready,visibilityConfigured]);
  const categories:any[]=useMemo(()=>((data?.categories||[]).filter((category:any)=>category.id)),[data]);
  const cards=useMemo(()=>((data?.categories||[]).filter((category:any)=>visible.includes(category.id||'uncategorized'))),[data,visible]);
  const categoryPath=(category:any)=>{const names=[category.name],seen=new Set([category.id]);let parentId=category.parent_id;while(parentId&&!seen.has(parentId)){const parent=categories.find(item=>item.id===parentId);if(!parent)break;names.unshift(parent.name);seen.add(parent.id);parentId=parent.parent_id;}return names.join(' › ');};
  const toggleCategory=(id:string)=>{setVisibilityConfigured(true);setVisible(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);};
  async function openDetails(category:any){setSelected(category);setDetails([]);try{const params=new URLSearchParams({start_date:startDate,end_date:endDate});if(category.id)params.set('category_id',category.id);else params.set('uncategorized','true');setDetails((await api(`/category-tracker/transactions?${params}`)).items);}catch(caught){setError(caught instanceof Error?caught.message:'Could not load category transactions');}}
  async function addCategory(event:React.FormEvent){event.preventDefault();setSaving(true);try{await api('/categories',{method:'POST',body:JSON.stringify({name:newName,kind:newKind,parent_id:newParentId||null})});setNewName('');setNewParentId('');await load();setMessage('Category added.');}catch(caught){setError(caught instanceof Error?caught.message:'Could not add category');}finally{setSaving(false);}}
  async function renameCategory(event:React.FormEvent){event.preventDefault();if(!editing)return;setSaving(true);try{await api(`/categories/${editing.id}`,{method:'PATCH',body:JSON.stringify({name:editName})});setEditing(null);await load();setMessage('Category renamed.');}catch(caught){setError(caught instanceof Error?caught.message:'Could not rename category');}finally{setSaving(false);}}
  async function deleteCategory(){if(!deleting||!replacementId)return;setSaving(true);try{await api(`/categories/${deleting.id}`,{method:'DELETE',body:JSON.stringify({replacement_category_id:replacementId})});setDeleting(null);setReplacementId('');setVisible(current=>current.filter(id=>id!==deleting.id));setVisibilityConfigured(true);await load();setMessage('Category deleted and its transactions reassigned.');}catch(caught){setError(caught instanceof Error?caught.message:'Could not delete category');}finally{setSaving(false);}}
  const [message,setMessage]=useState('');
  return <Protected><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="label">Spending organization</p><h1 className="text-3xl font-bold">Category tracker</h1><p className="mt-1 text-slate-500">Review category totals and drill into the transactions behind each one.</p></div><button type="button" onClick={()=>setManagerOpen(true)} className="rounded bg-navy px-4 py-2 text-sm font-medium text-white">Manage categories</button></header>
    <section className="card mt-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm"><span className="label block">From date</span><input type="date" className="mt-1 w-full rounded border p-2" value={startDate} max={endDate} onChange={event=>setStartDate(event.target.value)}/></label><label className="text-sm"><span className="label block">To date</span><input type="date" className="mt-1 w-full rounded border p-2" value={endDate} min={startDate} onChange={event=>setEndDate(event.target.value)}/></label></div><details className="mt-5 rounded-lg border bg-slate-50 p-3" open><summary className="cursor-pointer text-sm font-medium">Show or hide category cards</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(data?.categories||[]).map((category:any)=>{const id=category.id||'uncategorized';return <label key={id} className="flex items-center gap-2 rounded bg-white p-2 text-sm"><input type="checkbox" checked={visible.includes(id)} onChange={()=>toggleCategory(id)}/>{category.name}</label>;})}</div></details></section>
    {message&&<p className="mt-4 rounded bg-emerald-50 p-3 text-sm text-emerald-800" role="status">{message}</p>}{error&&<p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!data?<p className="mt-8 text-slate-500">Loading categories…</p>:<><p className="mt-5 text-sm text-slate-500">{data.start_date} through {data.end_date} · {cards.length} category cards shown</p><section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map((category:any)=><button type="button" key={category.id||'uncategorized'} onClick={()=>void openDetails(category)} className="card text-left transition hover:-translate-y-0.5 hover:ring-2 hover:ring-mint/60"><div className="flex items-start justify-between gap-3"><div><p className="label">{category.kind}</p><h2 className="mt-1 text-lg font-semibold">{categoryPath(category)}</h2></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600">{category.transaction_count} txns</span></div><p className={`mt-5 text-3xl font-bold ${category.net_amount<0?'text-rose-700':'text-emerald-700'}`}>{money(category.net_amount)}</p><p className="mt-1 text-xs text-slate-500">Net amount</p><dl className="mt-4 grid grid-cols-2 gap-3 border-t pt-3 text-sm"><div><dt className="text-slate-500">Debits</dt><dd className="mt-1 font-medium text-rose-700">{money(category.debits)}</dd></div><div><dt className="text-slate-500">Credits</dt><dd className="mt-1 font-medium text-emerald-700">{money(category.credits)}</dd></div></dl><p className="mt-4 text-xs font-medium text-navy">View transactions →</p></button>)}</section></>}
    {managerOpen&&<div className="fixed inset-0 z-50 flex items-end bg-slate-900/40 sm:items-center sm:justify-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="category-manager-title"><div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-t-2xl bg-white p-5 shadow-xl sm:rounded-2xl"><div className="flex justify-between gap-4"><div><h2 id="category-manager-title" className="text-lg font-semibold">Manage categories</h2><p className="mt-1 text-sm text-slate-500">Create categories or nest a child below any parent. Children inherit their parent’s category rules.</p></div><button type="button" onClick={()=>setManagerOpen(false)} aria-label="Close">×</button></div><form onSubmit={addCategory} className="mt-5 grid gap-3 rounded-xl border bg-slate-50 p-4 sm:grid-cols-2"><input className="rounded border p-2" placeholder="Category name, e.g. Phone Bill" value={newName} onChange={event=>setNewName(event.target.value)} required/><select className="rounded border p-2" value={newParentId} onChange={event=>setNewParentId(event.target.value)}><option value="">Top-level category</option>{categories.map(category=><option key={category.id} value={category.id}>{categoryPath(category)}</option>)}</select><select className="rounded border p-2" value={newKind} disabled={!!newParentId} onChange={event=>setNewKind(event.target.value)}><option value="expense">Expense</option><option value="income">Income</option><option value="transfer">Transfer</option><option value="other">Other</option></select><button disabled={saving} className="rounded bg-navy px-4 py-2 text-sm text-white disabled:opacity-50">Add category</button>{newParentId&&<p className="sm:col-span-2 text-xs text-slate-500">The child inherits its parent’s kind, essential default, and savings-rule behavior.</p>}</form><div className="mt-5 space-y-2">{categories.map(category=><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3" key={category.id}><div><b>{categoryPath(category)}</b><p className="text-xs capitalize text-slate-500">{category.kind}{category.parent_id?' · inherited parent rules':''}</p></div><div className="flex gap-3 text-sm"><button type="button" className="text-navy underline" onClick={()=>{setEditing(category);setEditName(category.name);}}>Rename</button><button type="button" className="text-red-700 underline" onClick={()=>{setDeleting(category);setReplacementId('');}}>Remove</button></div></div>)}</div></div></div>}
    {editing&&<div className="fixed inset-0 z-[60] grid place-items-center bg-slate-900/40 p-4" role="dialog" aria-modal="true" aria-labelledby="rename-category-title"><form onSubmit={renameCategory} className="w-full max-w-md rounded-2xl bg-white p-5 shadow-xl"><h2 id="rename-category-title" className="text-lg font-semibold">Rename category</h2><input className="mt-4 w-full rounded border p-2" value={editName} onChange={event=>setEditName(event.target.value)} required autoFocus/><div className="mt-5 flex justify-end gap-2"><button type="button" className="rounded border px-4 py-2" onClick={()=>setEditing(null)}>Cancel</button><button disabled={saving} className="rounded bg-navy px-4 py-2 text-white">Save</button></div></form></div>}
    {deleting&&<div className="fixed inset-0 z-[60] grid place-items-center bg-slate-900/40 p-4" role="dialog" aria-modal="true" aria-labelledby="delete-category-title"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-xl"><h2 id="delete-category-title" className="text-lg font-semibold">Remove {deleting.name}?</h2><p className="mt-2 text-sm text-slate-600">This does not delete transactions. Choose the category that should replace it for every transaction and savings rule currently using it.</p><label className="label mt-5 block">Move existing items to</label><select className="mt-1 w-full rounded border p-2" value={replacementId} onChange={event=>setReplacementId(event.target.value)}><option value="">Choose replacement category</option>{categories.filter(category=>category.id!==deleting.id).map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select><div className="mt-5 flex justify-end gap-2"><button type="button" className="rounded border px-4 py-2" onClick={()=>setDeleting(null)}>Cancel</button><button type="button" disabled={!replacementId||saving} onClick={()=>void deleteCategory()} className="rounded bg-red-700 px-4 py-2 text-white disabled:opacity-50">Reassign and remove</button></div></div></div>}
    {selected&&<div className="fixed inset-0 z-50 flex items-end bg-slate-900/40 sm:items-center sm:justify-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="category-details-title"><div className="max-h-[85vh] w-full max-w-3xl overflow-y-auto rounded-t-2xl bg-white p-5 shadow-xl sm:rounded-2xl"><div className="flex items-start justify-between gap-4"><div><h2 id="category-details-title" className="text-lg font-semibold">{selected.name} transactions</h2><p className="mt-1 text-sm text-slate-500">{startDate} through {endDate} · {details.length} transactions</p></div><button type="button" className="rounded px-2 py-1 text-slate-500 hover:bg-slate-100" onClick={()=>setSelected(null)} aria-label="Close">×</button></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="pb-2">Date</th><th className="pb-2">Description</th><th className="pb-2">Account</th><th className="pb-2 text-right">Amount</th></tr></thead><tbody>{details.map((item:any)=><tr className="border-b last:border-0" key={item.id}><td className="py-3">{item.date}</td><td>{item.description}</td><td className="text-slate-500">{item.account_name}</td><td className={Number(item.amount)<0?'text-right text-rose-700':'text-right text-emerald-700'}>{money(item.amount)}</td></tr>)}{!details.length&&<tr><td className="py-6 text-slate-500" colSpan={4}>No transactions in this category for the selected range.</td></tr>}</tbody></table></div><button type="button" className="mt-5 w-full rounded bg-navy px-4 py-2 text-sm font-medium text-white" onClick={()=>setSelected(null)}>Done</button></div></div>}
  </Protected>;
}
