'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { api, money } from '@/lib/api';
import { Protected } from '@/components/protected';

const today = new Date().toISOString().slice(0, 10);
const monthStart = `${today.slice(0, 8)}01`;

export default function CategoryTracker() {
  const [startDate, setStartDate] = useState(monthStart), [endDate, setEndDate] = useState(today), [data, setData] = useState<any|null>(null), [visible, setVisible] = useState<string[]>([]), [selected, setSelected] = useState<any|null>(null), [details, setDetails] = useState<any[]>([]), [error, setError] = useState('');
  const load = useCallback(async () => { try { const result=await api(`/category-tracker?start_date=${startDate}&end_date=${endDate}`); setData(result); setVisible((current) => current.length ? current : result.categories.map((category:any) => category.id || 'uncategorized')); setError(''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not load category totals'); } }, [startDate,endDate]);
  useEffect(() => { void load(); window.addEventListener('pfos-view-change', load); return () => window.removeEventListener('pfos-view-change',load); }, [load]);
  const cards = useMemo(() => (data?.categories || []).filter((category:any) => visible.includes(category.id || 'uncategorized')), [data,visible]);
  function toggleCategory(id:string) { setVisible((current) => current.includes(id) ? current.filter((currentId) => currentId !== id) : [...current,id]); }
  async function openDetails(category:any) { setSelected(category); setDetails([]); try { const params=new URLSearchParams({start_date:startDate,end_date:endDate}); if (category.id) params.set('category_id',category.id); else params.set('uncategorized','true'); const result=await api(`/category-tracker/transactions?${params}`); setDetails(result.items); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not load category transactions'); } }
  return <Protected><header><p className="label">Spending organization</p><h1 className="text-3xl font-bold">Category tracker</h1><p className="mt-1 text-slate-500">Review category totals and drill into the transactions behind each one.</p></header>
    <section className="card mt-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm"><span className="label block">From date</span><input type="date" className="mt-1 w-full rounded border p-2" value={startDate} max={endDate} onChange={(event) => setStartDate(event.target.value)}/></label><label className="text-sm"><span className="label block">To date</span><input type="date" className="mt-1 w-full rounded border p-2" value={endDate} min={startDate} onChange={(event) => setEndDate(event.target.value)}/></label></div><details className="mt-5 rounded-lg border bg-slate-50 p-3" open><summary className="cursor-pointer text-sm font-medium">Show or hide category cards</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(data?.categories || []).map((category:any) => { const id=category.id || 'uncategorized'; return <label key={id} className="flex items-center gap-2 rounded bg-white p-2 text-sm"><input type="checkbox" checked={visible.includes(id)} onChange={() => toggleCategory(id)}/>{category.name}</label>; })}</div></details></section>
    {error && <p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!data ? <p className="mt-8 text-slate-500">Loading categories…</p> : <><p className="mt-5 text-sm text-slate-500">{data.start_date} through {data.end_date} · {cards.length} category cards shown</p><section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map((category:any) => <button type="button" key={category.id || 'uncategorized'} onClick={() => void openDetails(category)} className="card text-left transition hover:-translate-y-0.5 hover:ring-2 hover:ring-mint/60"><div className="flex items-start justify-between gap-3"><div><p className="label">{category.kind}</p><h2 className="mt-1 text-lg font-semibold">{category.name}</h2></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600">{category.transaction_count} txns</span></div><p className={`mt-5 text-3xl font-bold ${category.net_amount < 0 ? 'text-rose-700' : 'text-emerald-700'}`}>{money(category.net_amount)}</p><p className="mt-1 text-xs text-slate-500">Net amount</p><dl className="mt-4 grid grid-cols-2 gap-3 border-t pt-3 text-sm"><div><dt className="text-slate-500">Debits</dt><dd className="mt-1 font-medium text-rose-700">{money(category.debits)}</dd></div><div><dt className="text-slate-500">Credits</dt><dd className="mt-1 font-medium text-emerald-700">{money(category.credits)}</dd></div></dl><p className="mt-4 text-xs font-medium text-navy">View transactions →</p></button>)}</section></>}
    {selected && <div className="fixed inset-0 z-50 flex items-end bg-slate-900/40 sm:items-center sm:justify-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="category-details-title"><div className="max-h-[85vh] w-full max-w-3xl overflow-y-auto rounded-t-2xl bg-white p-5 shadow-xl sm:rounded-2xl"><div className="flex items-start justify-between gap-4"><div><h2 id="category-details-title" className="text-lg font-semibold">{selected.name} transactions</h2><p className="mt-1 text-sm text-slate-500">{startDate} through {endDate} · {details.length} transactions</p></div><button type="button" className="rounded px-2 py-1 text-slate-500 hover:bg-slate-100" onClick={() => setSelected(null)} aria-label="Close">×</button></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="pb-2">Date</th><th className="pb-2">Description</th><th className="pb-2">Account</th><th className="pb-2 text-right">Amount</th></tr></thead><tbody>{details.map((item:any) => <tr className="border-b last:border-0" key={item.id}><td className="py-3">{item.date}</td><td>{item.description}</td><td className="text-slate-500">{item.account_name}</td><td className={Number(item.amount) < 0 ? 'text-right text-rose-700' : 'text-right text-emerald-700'}>{money(item.amount)}</td></tr>)}{!details.length && <tr><td className="py-6 text-slate-500" colSpan={4}>No transactions in this category for the selected range.</td></tr>}</tbody></table></div><button type="button" className="mt-5 w-full rounded bg-navy px-4 py-2 text-sm font-medium text-white" onClick={() => setSelected(null)}>Done</button></div></div>}
  </Protected>;
}
